rin:
  num_layers: "2,2,2"
  latent_slots: 128
  latent_dim: 512
  latent_mlp_ratio: 4
  latent_num_heads: 16
  tape_dim: 256
  tape_mlp_ratio: 2
  rw_num_heads: 8
  image_height: 32
  image_width: 32
  image_channels: 3
  patch_size: 2
  latent_pos_encoding: "learned"
  tape_pos_encoding: "learned"
  drop_path: 0.1
  drop_units: 0.1
  drop_att: 0.0
  time_scaling: 1000
  self_cond: "latent"
  time_on_latent: true
  cond_on_latent_n: 1
  cond_tape_writable: false
  cond_dim: 0
  cond_proj: true
  cond_decoupled_read: false
  xattn_enc_ln: false
  num_classes: 10

diffusion:
  train_schedule: "sigmoid@-3,3,0.9"
  inference_schedule: "cosine"
  pred_type: "eps"
  self_cond: "latent"
  loss_type: "eps"
  cond_dropout: 0.1
  guidance: 3.0
  num_classes: 10

trainer:
  num_classes: 10
  train_num_steps: 300000
  train_batch_size: 256
  split_batches: true
  fp16: false
  amp: false
  lr_scheduler_name: "cosine"
  lr: 0.003
  lr_warmup_steps: 10000
  optimizer_name: "lamb"
  optimizer_exclude_weight_decay: ["bias", "beta", "gamma"]
  optimizer_kwargs:
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: !!float 1e-8
  clip_grad_norm: 1.0
  sample_every: 1000
  num_dl_workers: 2
  ema_decay: 0.9999
  ema_update_every: 1
  sampling_kwargs:
    iterations: 1000
    method: "ddpm"
  checkpoint_folder: "/home/stud/ljul/storage/user/cifar/"
  run_name: "rin_cifar_cfg_vanilla_300k"
  log_to_wandb: true 
  log_every_n_steps: 10

run:
  vanilla: false
  cifar: true